export const PG_CHART_CONFIG = {
  grid: { stroke: "rgba(255, 255, 255, 0.18)", strokeDasharray: "3 4" },
  axis: {
    tick: { fill: "#c8ced8", fontSize: 11, fontFamily: "Manrope, sans-serif", fontWeight: 600 },
    axisLine: { stroke: "rgba(255,255,255,0.22)" },
    tickLine: false,
    tickMargin: 8,
  },
  tooltip: {
    contentStyle: {
      backgroundColor: "rgba(18, 20, 25, 0.92)",
      border: "1px solid rgba(255,255,255,0.24)",
      borderRadius: "12px",
      color: "#f5f7fa",
      fontSize: "13px",
      fontFamily: "Manrope, sans-serif",
      fontWeight: 600,
      letterSpacing: "0.01em",
      boxShadow: "0 12px 24px rgba(0, 0, 0, 0.28)",
    },
    itemStyle: {
      color: "#f5f7fa",
      fontFamily: "Manrope, sans-serif",
      fontWeight: 600,
    },
    labelStyle: {
      color: "#c8ced8",
      fontFamily: "Manrope, sans-serif",
      fontWeight: 600,
    },
  },
  legend: {
    iconType: "circle",
    wrapperStyle: {
      color: "#d7dde7",
      fontFamily: "Manrope, sans-serif",
      fontSize: "12px",
      fontWeight: 600,
      letterSpacing: "0.01em",
      paddingTop: "8px",
    },
  },
  series: {
    primary: "#f5f7fa",
    secondary: "#c9d0db",
    tertiary: "#a4adbb",
    quaternary: "#8a93a3",
    quinary: "#727b8b",
    positive: "#dfe4ec",
    negative: "#858f9f",
    muted: "#616b7d",
  },
  materialColors: {
    Cement: "#f5f7fa",
    Conductor: "#c9d0db",
    Insulator: "#a4adbb",
    Steel: "#8a93a3",
    Transformer: "#727b8b",
  },
  phaseColors: {
    Planning: "#f0f3f8",
    Execution: "#aeb7c5",
    Commissioning: "#727b8b",
  },
  towerColors: {
    "220kV": "#f0f3f8",
    "400kV": "#aeb7c5",
    "765kV": "#727b8b",
  },
  regionColors: {
    East: "#eef2f8",
    North: "#c9d0db",
    South: "#a4adbb",
    West: "#7b8495",
  },
};
