server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  gzip on;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://powergrid-backend:8080;
    proxy_read_timeout 120s;
  }
}
